# Generated by Django 4.2.7 on 2025-11-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Ghana', max_length=100, verbose_name='country'),
        ),
    ]
