# Generated by Django 4.2.7 on 2025-11-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='verification_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verification approved at'),
        ),
        migrations.AddField(
            model_name='store',
            name='verification_notes',
            field=models.TextField(blank=True, verbose_name='verification notes'),
        ),
        migrations.AddField(
            model_name='store',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Verification Rejected')], default='unverified', max_length=20, verbose_name='verification status'),
        ),
        migrations.AddField(
            model_name='store',
            name='verification_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verification submitted at'),
        ),
        migrations.CreateModel(
            name='StoreVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, verbose_name='business name')),
                ('business_registration_number', models.CharField(blank=True, max_length=100, verbose_name='business registration number')),
                ('tax_identification_number', models.CharField(blank=True, max_length=100, verbose_name='tax identification number')),
                ('business_address', models.TextField(verbose_name='business address')),
                ('business_phone', models.CharField(blank=True, max_length=20, verbose_name='business phone')),
                ('business_email', models.EmailField(blank=True, max_length=254, verbose_name='business email')),
                ('business_type', models.CharField(max_length=100, verbose_name='business type')),
                ('years_in_business', models.CharField(blank=True, max_length=20, verbose_name='years in business')),
                ('description_of_business', models.TextField(blank=True, verbose_name='description of business')),
                ('owner_name', models.CharField(max_length=200, verbose_name='owner name')),
                ('owner_phone', models.CharField(blank=True, max_length=20, verbose_name='owner phone')),
                ('owner_email', models.EmailField(blank=True, max_length=254, verbose_name='owner email')),
                ('business_registration', models.FileField(blank=True, null=True, upload_to='verification/business/')),
                ('tax_certificate', models.FileField(blank=True, null=True, upload_to='verification/tax/')),
                ('owner_id', models.FileField(blank=True, null=True, upload_to='verification/id/')),
                ('business_permit', models.FileField(blank=True, null=True, upload_to='verification/permit/')),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to='verification/bank/')),
                ('social_media_links', models.JSONField(blank=True, default=dict, verbose_name='social media links')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_data', to='stores.store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'store verification',
                'verbose_name_plural': 'store verifications',
            },
        ),
    ]
