# Generated by Django 4.2.7 on 2025-11-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='GHS', max_length=3, verbose_name='currency'),
        ),
    ]
